- name: clone modified caddy
  ansible.builtin.git:
    repo: 'https://github.com/kmpm/caddy-loopia-propagation'
    dest: "{{ faasd_caddy_propagation }}"
  register: gitclone

- name: build modified caddy
  shell:
    cmd: make
    chdir: "{{ faasd_caddy_propagation }}"
    creates: "{{ faasd_caddy_build_output }}"
  register: xcaddy_build
  environment:
    - binfile: "{{ faasd_caddy_build_output }}"
    - PATH: "/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin"
    - GOENV: "{{ faasd_caddy_propagation }}/var/go"
    - GOCACHE: "{{ faasd_caddy_propagation }}/var/go-build"
    - MODCACHE: "{{ faasd_caddy_propagation }}/var/pkg/mod"
  when: gitclone.changed

- debug: var=xcaddy_build.stderr_lines
  when: xcaddy_build is defined and xcaddy_build.stderr_lines is defined

