---
- name: Install required dependencies using apt
  apt:
    cache_valid_time: 3600
    pkg:
      - curl
      - runc
      - bridge-utils
  when: ansible_os_family == 'Debian'

- name: Install required dependencies using yum
  yum:
    name:
      - curl 
      - runc
  when: ansible_os_family == 'RedHat'

- name: "download faasd {{ faasd_version }}"
  get_url:
    url: "https://github.com/openfaas/faasd/releases/download/{{ faasd_version }}/faasd{{ faasd_faasd_suffix }}"
    dest: /usr/local/bin/faasd
    mode: '0755'

- name: update current version in custom facts
  ini_file:
    path: /etc/ansible/facts.d/faasd.fact
    section: current
    option: version
    value: "{{ faasd_version }}"
    mode: '0644'
  notify:
    - reload ansible_local
