---
# handlers file for faasd

- name: "reload ansible_local"
  setup:
    filter: "ansible_local"

- name: wait for 5
  pause:
    seconds: 5


- name: restart containerd
  systemd:
    name: containerd
    state: restarted
  tags: molecule-notest