---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO:-debian11}"
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
