---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    # capabilities:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # privileged: true
  - name: instance2
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
