---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks: 
    - name: caddy- stat Caddyfile 
      stat:
        path: /etc/caddy/Caddyfile
      register: stat_result
    - name: caddy - check caddyfile exists
      assert:
        that:
          - stat_result.stat.exists
      
