---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars: 
    - faasd_embed_caddy: no
  gather_facts: false
  tasks: 
    - name: faasd - faasd-provider.service
      lineinfile:
        name: "/tmp"
    
    - name: fact - stat factfile
      stat:
        path: /etc/ansible/facts.d/faasd.fact
      register: stat_fact
    
    - name: fact - verify existance
      assert:
        that:
          - stat_fact.stat.exists

