---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: faasd

      - name: Set up Python ${{ matrix.python-version }}.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies.
        run: |
          ls -la
          python3 -m pip install --upgrade pip
          python3 -m pip install -r faasd/requirements.txt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          # MOLECULE_DISTRO: ${{ matrix.distro }}
        

